# Generated by Django 3.2.20 on 2023-07-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='contact_way',
        ),
    ]
